### ISSUE TITLE
Links broken!

### ISSUE THREAD

**Issue by ThamesDev** [ThamesDev/rpi-mc-server_1.0-1_arm32#8]
The link from about.md to installation.md seems not to be working. It appears that it's linking to `thamesdev.github.io/installation.html`, whereas the correct link would be `thamesdev.github.io/rpi-mc-server_1.0-1_arm32/installation.html`, I suspect that this will be the same for the other links?

**Comment by rebal15** [comment]
Yep sorry bout that, you can fix if you want.

**Comment by ThamesDev** [comment]
Done!
